# Generated by Django 4.0.4 on 2022-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
